### ISSUE TITLE
Mongo, repl db support

### ISSUE THREAD

**Issue by NoodlesDev987** [Fizuku/hexoshard-glitch#2]
Hi, can you please add MongoDB and replit db support to hexo shard?

**Comment by Fizuku** [comment]
> Hi, can you please add MongoDB and replit db support to hexo shard?

Sorry, but HexoDB lost support. Also, MongoDB and Repl.itDB have their own respective node packages at NPM. Alternatively, I recommend checking out Quickmongo at npm.com. Have a great day!🙏
